name: Build built branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build --wheel

      - name: Replace working tree with wheel
        run: |
          shopt -s extglob
          rm -rf !("dist")
          unzip -o dist/*.whl -d .
          rm -rf dist

      - name: Push to built branch
        uses: ad-m/github-push-action@master
        with:
          branch: built
          force: true
